USE recordr;



CREATE TABLE IF NOT EXISTS `auditlogs` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `UserId` int(11) NOT NULL,
  `Action` ENUM('CREATE', 'UPDATE', 'DELETE') CHARACTER SET utf8mb4 NOT NULL,
  `Target` ENUM('RECORD', 'CONTAINER', 'VOLUME') CHARACTER SET utf8mb4 NOT NULL,
  `TargetId` INT(11) NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`Id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8
